//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Predictor.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.Predictions = new HashSet<Prediction>();
        }
    
        public int Id { get; set; }
        public int TrounamentId { get; set; }
        public string NationCodeHome { get; set; }
        public string NationCodeAway { get; set; }
        public System.DateTime MatchStartTime { get; set; }
        public Nullable<byte> ScoreHome { get; set; }
        public Nullable<byte> ScoreAway { get; set; }
        public string Remark { get; set; }
    
        public virtual Nation Nation { get; set; }
        public virtual Nation Nation1 { get; set; }
        public virtual Tournament Tournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prediction> Predictions { get; set; }
    }
}
